"""
EGN 310 Data Structures
Module 5: Recursion Set (test file)

Do not edit this file. Make these tests pass by editing recursion_set.py.

Run with:
    pytest test_recursion.py -v
or:
    python test_recursion.py
"""

import ast
import inspect

from recursion_set import (
    factorial,
    sum_digits,
    reverse_string,
    power,
    power_iterative,
)


# ---------------------------------------------------------------
# Helper: checks that a function really is recursive
# (it calls itself and contains no for/while loops)
# ---------------------------------------------------------------
def is_recursive_without_loops(func):
    source = inspect.getsource(func)
    tree = ast.parse(source)
    name = func.__name__
    calls_itself = False
    has_loop = False
    for node in ast.walk(tree):
        if isinstance(node, (ast.For, ast.While)):
            has_loop = True
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id == name:
                calls_itself = True
    return calls_itself and not has_loop


# ---------------------------------------------------------------
# Function 1: factorial
# ---------------------------------------------------------------
def test_factorial_base_case():
    assert factorial(0) == 1


def test_factorial_one():
    assert factorial(1) == 1


def test_factorial_small():
    assert factorial(5) == 120


def test_factorial_larger():
    assert factorial(10) == 3628800


def test_factorial_is_recursive():
    assert is_recursive_without_loops(factorial), \
        "factorial must call itself and must not use loops"


# ---------------------------------------------------------------
# Function 2: sum_digits
# ---------------------------------------------------------------
def test_sum_digits_zero():
    assert sum_digits(0) == 0


def test_sum_digits_single_digit():
    assert sum_digits(7) == 7


def test_sum_digits_multi_digit():
    assert sum_digits(472) == 13


def test_sum_digits_with_zeros():
    assert sum_digits(1005) == 6


def test_sum_digits_is_recursive():
    assert is_recursive_without_loops(sum_digits), \
        "sum_digits must call itself and must not use loops"


# ---------------------------------------------------------------
# Function 3: reverse_string
# ---------------------------------------------------------------
def test_reverse_empty():
    assert reverse_string("") == ""


def test_reverse_one_char():
    assert reverse_string("a") == "a"


def test_reverse_word():
    assert reverse_string("cat") == "tac"


def test_reverse_palindrome():
    assert reverse_string("racecar") == "racecar"


def test_reverse_with_spaces():
    assert reverse_string("hi there") == "ereht ih"


def test_reverse_is_recursive():
    assert is_recursive_without_loops(reverse_string), \
        "reverse_string must call itself and must not use loops"


# ---------------------------------------------------------------
# Function 4: power (converted from iterative)
# ---------------------------------------------------------------
def test_power_exponent_zero():
    assert power(7, 0) == 1


def test_power_exponent_one():
    assert power(9, 1) == 9


def test_power_small():
    assert power(2, 5) == 32


def test_power_base_one():
    assert power(1, 50) == 1


def test_power_matches_iterative():
    # The recursive version must agree with the provided iterative one
    for base in range(0, 6):
        for exp in range(0, 8):
            assert power(base, exp) == power_iterative(base, exp), \
                f"power({base}, {exp}) does not match power_iterative"


def test_power_is_recursive():
    assert is_recursive_without_loops(power), \
        "power must call itself and must not use loops"


# ---------------------------------------------------------------
# Simple runner so students can use plain "python test_recursion.py"
# ---------------------------------------------------------------
if __name__ == "__main__":
    tests = [
        (name, obj) for name, obj in sorted(globals().items())
        if name.startswith("test_") and callable(obj)
    ]
    passed = 0
    for name, test in tests:
        try:
            test()
            print(f"PASS  {name}")
            passed += 1
        except AssertionError as e:
            print(f"FAIL  {name}  {e}")
        except Exception as e:
            print(f"ERROR {name}  {type(e).__name__}: {e}")
    print(f"\n{passed} of {len(tests)} tests passed")
